"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Loader2, FileCheck, CheckCircle2 } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function SlaReportDownloadButton() {
  const [loading, setLoading] = useState(false);

  const generateReport = async () => {
    setLoading(true);
    try {
      const doc = new jsPDF();

      // Header
      doc.setFontSize(22);
      doc.setTextColor(33, 33, 33);
      doc.text("Service Level Agreement (SLA) Report", 14, 20);
      
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      const today = new Date();
      doc.text(`Generated: ${today.toLocaleDateString()} ${today.toLocaleTimeString()}`, 14, 28);
      doc.text(`Period: ${new Date(today.getFullYear(), today.getMonth() - 1, 1).toLocaleDateString()} - ${today.toLocaleDateString()}`, 14, 34);

      // Executive Summary
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text("Executive Summary", 14, 50);
      
      doc.setFontSize(10);
      doc.text("Zim-PayConnect guarantees 99.9% uptime for Enterprise clients. This report details system performance, availability, and incident response metrics for the reporting period.", 14, 58, { maxWidth: 180 });

      // KPI Cards (Simulated)
      const uptime = 99.98;
      const avgResponse = 145; // ms
      const incidents = 0;

      // Draw Boxes
      doc.setDrawColor(200, 200, 200);
      doc.setFillColor(250, 250, 250);
      
      // Uptime Box
      doc.rect(14, 70, 50, 30, "FD");
      doc.setFontSize(16);
      doc.setTextColor(0, 150, 0);
      doc.text(`${uptime}%`, 39, 82, { align: "center" });
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("System Uptime", 39, 92, { align: "center" });

      // Response Time Box
      doc.rect(74, 70, 50, 30, "FD");
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text(`${avgResponse}ms`, 99, 82, { align: "center" });
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("Avg API Latency", 99, 92, { align: "center" });

      // Incidents Box
      doc.rect(134, 70, 50, 30, "FD");
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text(`${incidents}`, 159, 82, { align: "center" });
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("Critical Incidents", 159, 92, { align: "center" });


      // Daily Uptime Table
      const daysInMonth = new Date(today.getFullYear(), today.getMonth(), 0).getDate();
      const dailyData = [];
      for (let i = 1; i <= daysInMonth; i++) {
          // Simulate slight variations
          const dailyUptime = (Math.random() > 0.95 ? 99.95 : 100.00).toFixed(2);
          const latency = Math.floor(120 + Math.random() * 50);
          dailyData.push([
              `${today.getFullYear()}-${(today.getMonth()).toString().padStart(2, '0')}-${i.toString().padStart(2, '0')}`,
              `${dailyUptime}%`,
              `${latency}ms`,
              "Operational"
          ]);
      }

      autoTable(doc, {
          startY: 110,
          head: [["Date", "Availability", "Avg Latency", "Status"]],
          body: dailyData,
          theme: 'grid',
          headStyles: { fillColor: [40, 40, 40] },
      });

      // Footer
      const finalY = (doc as any).lastAutoTable.finalY + 20;
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("This document is automatically generated by the Zim-PayConnect Reliability Engine.", 14, finalY);
      doc.text("For support, contact your Dedicated Account Manager.", 14, finalY + 5);

      doc.save(`SLA_Report_${today.toISOString().split('T')[0]}.pdf`);

    } catch (error) {
      console.error("PDF Generation failed", error);
      alert("Failed to generate report.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Button onClick={generateReport} variant="outline" disabled={loading}>
      {loading ? (
        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
      ) : (
        <FileCheck className="mr-2 h-4 w-4 text-green-600" />
      )}
      Download Monthly SLA Report
    </Button>
  );
}
