-- AlterTable
ALTER TABLE "Organization" ADD COLUMN     "defaultCurrency" TEXT NOT NULL DEFAULT 'USD',
ADD COLUMN     "necEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "necRate" DECIMAL(5,4) NOT NULL DEFAULT 0.0,
ADD COLUMN     "nssaCeilingUSD" DECIMAL(10,2) NOT NULL DEFAULT 700.00,
ADD COLUMN     "nssaCeilingZiG" DECIMAL(12,2) NOT NULL DEFAULT 19600.00,
ADD COLUMN     "nssaEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "nssaRate" DECIMAL(5,4) NOT NULL DEFAULT 0.045,
ADD COLUMN     "sdfEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "sdfRate" DECIMAL(5,4) NOT NULL DEFAULT 0.01,
ALTER COLUMN "trialEndsAt" SET DEFAULT NOW() + interval '7 days';
