import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import JSZip from "jszip";
import { TaxResult, RawPayrollRecord } from "@/lib/ephemeral-engine/types";
import { generateZimraXml } from "@/lib/xml-generator";
import { generateGLCSV, GLFormat } from "@/lib/ephemeral-engine/gl-exporter";
import { sanitizeCsvCell, sanitizeFilename } from "@/lib/utils";
import { buildLoanScheduleCsv } from "@/lib/loan-schedule";

// Combine raw record and calculation result
type FullRecord = RawPayrollRecord & { taxResult: TaxResult };

export async function generatePayslipPDF(record: FullRecord, orgName: string, logoUrl?: string | null, removeBranding: boolean = false): Promise<ArrayBuffer> {
  const doc = new jsPDF();
  
  const yOffset = 20;

  // Add Logo if available
  if (logoUrl) {
    try {
        // Create an image element to load the logo
        // Note: In a browser environment, we might need to fetch the image data first
        // or use an existing Image object. For now, we'll try to add it directly if it's a base64 string
        // or a URL that jsPDF can handle (CORS might be an issue with external URLs).
        // Assuming Data URI or simple URL for now.
        
        // For simple URL implementation in client-side jsPDF:
        const img = new Image();
        img.src = logoUrl;
        await new Promise((resolve, reject) => {
             img.onload = resolve;
             img.onerror = reject;
        });
        
        // Calculate aspect ratio to fit in a box of 40x20
        const maxWidth = 40;
        const maxHeight = 20;
        const ratio = Math.min(maxWidth / img.width, maxHeight / img.height);
        const width = img.width * ratio;
        const height = img.height * ratio;

        doc.addImage(img, "PNG", 14, 10, width, height);
        
        // If logo is present, we might want to center the text relative to the page 
        // but keep the Y position similar or slightly adjusted.
    } catch (e) {
        console.warn("Failed to load logo", e);
    }
  }

  // Header
  doc.setFontSize(18);
  doc.text(orgName, 105, yOffset, { align: "center" });
  doc.setFontSize(14);
  doc.text("Payslip", 105, yOffset + 10, { align: "center" });
  
  doc.setFontSize(10);
  doc.text(`Employee: ${record.name} (${record.employeeId})`, 14, 45);
  doc.text(`TIN: ${record.tin || "N/A"}`, 14, 50);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 45);
  doc.text(`Currency: ${record.currency}`, 150, 50);
  doc.text(`Tax Method: ${record.taxResult.method || "PAYE"}`, 150, 55);

  // Table Data
  const { taxResult } = record;
  const currency = record.currency;
  
  const bodyData = [
    ["Basic Salary", `${currency} ${record.basicSalary.toFixed(2)}`],
    ["Allowances", `${currency} ${(record.allowances || 0).toFixed(2)}`],
    ...(record.exemptAllowances ? [["Exempt Allowances", `${currency} ${record.exemptAllowances.toFixed(2)}`]] : []),
    [{ content: "Gross Income", styles: { fontStyle: "bold" } }, { content: `${currency} ${taxResult.grossIncome.toFixed(2)}`, styles: { fontStyle: "bold" } }],
    ["", ""], // Spacer
    ["Deductions", ""],
    ["NSSA (Pension)", `-${currency} ${taxResult.nssa.toFixed(2)}`],
    ["NEC", `-${currency} ${(taxResult.nec || 0).toFixed(2)}`], // Handle undefined safely
    ["PAYE (Tax)", `-${currency} ${taxResult.paye.toFixed(2)}`],
    ["AIDS Levy", `-${currency} ${taxResult.aidsLevy.toFixed(2)}`],
    [{ content: "Total Deductions", styles: { fontStyle: "bold" } }, { content: `-${currency} ${taxResult.totalDeductions.toFixed(2)}`, styles: { fontStyle: "bold" } }],
    ["", ""], // Spacer
    [{ content: "NET PAY", styles: { fillColor: [220, 255, 220], fontStyle: "bold", fontSize: 12 } }, { content: `${currency} ${taxResult.netPay.toFixed(2)}`, styles: { fillColor: [220, 255, 220], fontStyle: "bold", fontSize: 12 } }]
  ];

  autoTable(doc, {
    startY: 65, // Adjusted down for extra header line
    head: [["Description", "Amount"]],
    body: bodyData as any,
    theme: "grid",
    headStyles: { fillColor: [40, 40, 40] },
    columnStyles: {
      0: { cellWidth: 120 },
      1: { cellWidth: 60, halign: "right" }
    }
  });

  // Footer
  if (!removeBranding) {
      const finalY = (doc as any).lastAutoTable.finalY + 20;
      doc.setFontSize(8);
      doc.text("Generated by Zim-PayConnect", 14, finalY);
  }
  
  return doc.output("arraybuffer");
}

export async function generateBatchZip(records: FullRecord[], orgName: string, logoUrl?: string | null, tin?: string, removeBranding: boolean = false, glFormat: GLFormat = "STANDARD"): Promise<Blob> {
  const zip = new JSZip();
  const rootFolder = zip.folder(`Payslips-${new Date().toISOString().split('T')[0]}`);

  // Split records
  const fdsRecords = records.filter(r => r.isPermanent !== false); // Default to true
  const nonFdsRecords = records.filter(r => r.isPermanent === false);

  const fdsFolder = fdsRecords.length > 0 ? rootFolder?.folder("FDS_Permanent") : null;
  const nonFdsFolder = nonFdsRecords.length > 0 ? rootFolder?.folder("Non_FDS_Casual") : null;

  // Helper to generate files for a batch
  const processBatch = async (batch: FullRecord[], folder: JSZip | null | undefined, summaryName: string) => {
    if (!batch.length || !folder) return;

    // PDFs
    for (const record of batch) {
      const pdfBuffer = await generatePayslipPDF(record, orgName, logoUrl, removeBranding);
      const safeName = sanitizeFilename(record.name, "employee");
      const safeId = sanitizeFilename(record.employeeId, "id");
      const fileName = `${safeName}_${safeId}.pdf`;
      folder.file(fileName, pdfBuffer);
    }

    // CSV Summary (with CSV injection hardening)
    let csvContent = `EmployeeID,Name,Gross,NSSA,NEC,Taxable,PAYE,AIDS_Levy,NetPay,SDF_Employer,Method,YTD_Gross,YTD_Tax_Paid
`;
    batch.forEach(r => {
      const t = r.taxResult;
      const row = [
        sanitizeCsvCell(String(r.employeeId)),
        sanitizeCsvCell(String(r.name)),
        t.grossIncome.toFixed(2),
        t.nssa.toFixed(2),
        (t.nec || 0).toFixed(2),
        t.taxableIncome.toFixed(2),
        t.paye.toFixed(2),
        t.aidsLevy.toFixed(2),
        t.netPay.toFixed(2),
        (t.sdf || 0).toFixed(2),
        sanitizeCsvCell(String(t.method || "PAYE")),
        String(r.ytdGross || 0),
        String(r.ytdTaxPaid || 0),
      ];
      csvContent += row.join(",") + "\n";
    });
    folder.file(summaryName, csvContent);
  };

  // Process both batches
  await processBatch(fdsRecords, fdsFolder, "FDS_Summary.csv");
  await processBatch(nonFdsRecords, nonFdsFolder, "Non_FDS_Summary.csv");

  // NSSA & NEC Contribution Schedules (POBF/NEC-friendly layouts)
  if (rootFolder) {
    const allRecords = [...fdsRecords, ...nonFdsRecords];

    // For NSSA we need organization context; we'll pass values via metadata in a future enhancement
    let nssaCsv = `Employer_Name,Employer_NSSA_Number,Employer_TIN,Pay_Year,Pay_Month,Employee_National_ID,Employee_NSSA_Number,Employee_Name,Employee_Payroll_No,Basic_Earnings,Other_Earnings,Total_Earnings,Employee_NSSA,Employer_NSSA,Total_NSSA
`;

    let necCsv = `Employer_Name,Employer_NEC_Number,Employer_TIN,Sector,Pay_Year,Pay_Month,Employee_Name,Employee_Payroll_No,NEC_Grade,Department,Cost_Center,Gross_Earnings,NEC_Employee,NEC_Employer,Total_NEC
`;

    const now = new Date();
    const payYear = now.getFullYear();
    const payMonth = (now.getMonth() + 1).toString().padStart(2, "0");

    allRecords.forEach((r) => {
      const t = r.taxResult;
      const gross = t.grossIncome;
      const otherEarnings = (r.allowances || 0) - (r.exemptAllowances || 0);

      if (t.nssa && t.nssa !== 0) {
        const employee = t.nssa;
        const employer = t.nssa; // 1:1 assumption
        const total = employee + employer;
        const row = [
          "", // Employer_Name (filled from org at export time if needed)
          "", // Employer_NSSA_Number
          "", // Employer_TIN
          payYear,
          payMonth,
          sanitizeCsvCell(r.nationalId || ""),
          "", // Employee_NSSA_Number (optional, not tracked yet)
          sanitizeCsvCell(r.name),
          sanitizeCsvCell(r.employeeId),
          r.basicSalary.toFixed(2),
          otherEarnings.toFixed(2),
          gross.toFixed(2),
          employee.toFixed(2),
          employer.toFixed(2),
          total.toFixed(2),
        ];
        nssaCsv += row.join(",") + "\n";
      }

      if (t.nec && t.nec !== 0) {
        const employeeNec = t.nec;
        const employerNec = t.nec; // 1:1 assumption
        const totalNec = employeeNec + employerNec;
        const row = [
          "", // Employer_Name
          "", // Employer_NEC_Number
          "", // Employer_TIN
          "", // Sector (can be populated from org.necSector if needed)
          payYear,
          payMonth,
          sanitizeCsvCell(r.name),
          sanitizeCsvCell(r.employeeId),
          sanitizeCsvCell(r.necGrade || ""),
          sanitizeCsvCell(r.department || ""),
          sanitizeCsvCell(r.costCenter || ""),
          gross.toFixed(2),
          employeeNec.toFixed(2),
          employerNec.toFixed(2),
          totalNec.toFixed(2),
        ];
        necCsv += row.join(",") + "\n";
      }
    });

    // Only attach files if there is at least one data row beyond header
    if (nssaCsv.trim().split("\n").length > 1) {
      rootFolder.file("NSSA_Contribution_Schedule.csv", nssaCsv);
    }
    if (necCsv.trim().split("\n").length > 1) {
      rootFolder.file("NEC_Return_Schedule.csv", necCsv);
    }
  }

  // Department / Cost Centre & Employer Cost Summaries
  if (rootFolder) {
    type GroupKey = string;
    interface Agg {
      gross: number;
      net: number;
      employerCost: number;
    }

    const deptMap = new Map<GroupKey, Agg>();
    const costCenterMap = new Map<GroupKey, Agg>();
    let totalEmployerCost = 0;

    const allRecords = [...fdsRecords, ...nonFdsRecords];

    allRecords.forEach((r) => {
      const t = r.taxResult;
      const employerNssa = t.nssa;
      const employerNec = t.nec || 0;
      const employerSdf = t.sdf || 0;
      const employerCost = employerNssa + employerNec + employerSdf;
      totalEmployerCost += employerCost;

      const updateAgg = (map: Map<GroupKey, Agg>, key: string) => {
        const k = key || "Unspecified";
        const current = map.get(k) || { gross: 0, net: 0, employerCost: 0 };
        current.gross += t.grossIncome;
        current.net += t.netPay;
        current.employerCost += employerCost;
        map.set(k, current);
      };

      if (r.department) {
        updateAgg(deptMap, r.department);
      }
      if (r.costCenter) {
        updateAgg(costCenterMap, r.costCenter);
      }
    });

    if (deptMap.size > 0) {
      let deptCsv = `Department,Gross,Net,Employer_Cost
`;
      for (const [dept, agg] of deptMap.entries()) {
        const row = [
          sanitizeCsvCell(dept),
          agg.gross.toFixed(2),
          agg.net.toFixed(2),
          agg.employerCost.toFixed(2),
        ];
        deptCsv += row.join(",") + "\n";
      }
      rootFolder.file("Department_Payroll_Summary.csv", deptCsv);
    }

    if (costCenterMap.size > 0) {
      let ccCsv = `Cost_Center,Gross,Net,Employer_Cost
`;
      for (const [cc, agg] of costCenterMap.entries()) {
        const row = [
          sanitizeCsvCell(cc),
          agg.gross.toFixed(2),
          agg.net.toFixed(2),
          agg.employerCost.toFixed(2),
        ];
        ccCsv += row.join(",") + "\n";
      }
      rootFolder.file("Cost_Center_Payroll_Summary.csv", ccCsv);
    }

    // Employer cost high-level summary
    if (allRecords.length > 0) {
      const employerCsv = `Metric,Value
Total_Employer_Cost,${totalEmployerCost.toFixed(2)}
Total_Employee_Count,${allRecords.length}
`;
      rootFolder.file("Employer_Cost_Summary.csv", employerCsv);
    }

    // Loan / Advance amortization schedule (if any loan metadata present)
    const loanCsv = buildLoanScheduleCsv(allRecords);
    if (loanCsv) {
      rootFolder.file("Loan_Amortization_Schedule.csv", loanCsv);
    }
  }

  // Generate ZIMRA XML Return (Combined)
  if (tin) {
      try {
          const xmlContent = generateZimraXml(records, orgName, tin);
          rootFolder?.file("Zimra_Return_XML.xml", xmlContent);
      } catch (e) {
          console.warn("Failed to generate ZIMRA XML", e);
      }
  }

  // Generate GL Export (Combined)
  try {
      const glCsv = generateGLCSV(records, orgName, glFormat);
      rootFolder?.file("General_Ledger.csv", glCsv);
  } catch (e) {
      console.warn("Failed to generate GL CSV", e);
  }

  return await zip.generateAsync({ type: "blob" });
}
