import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions for using the Zim-PayConnect payroll engine.",
};

export default function TermsPage() {
  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold">Terms of Service</h1>
      <p className="text-sm text-muted-foreground">Last Updated: February 12, 2026</p>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold">1. Acceptance of Terms</h2>
        <p>
          By accessing and using Zim-PayConnect ("the Service"), you agree to be bound by these Terms of Service. 
          If you do not agree to these terms, please do not use the Service.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold">2. Service Description ("As Is")</h2>
        <p>
          The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Zim-PayConnect makes no representations or warranties 
          of any kind, express or implied, as to the operation of the Service or the information, content, materials, or products 
          included on the Service.
        </p>
        <p>
          We explicitly disclaim all warranties, express or implied, including but not limited to implied warranties of merchantability 
          and fitness for a particular purpose.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold">3. No Tax Advice & Exchange Rates</h2>
        <p>
          The Service is a calculation and formatting tool designed to assist with payroll processing in accordance with 
          ZIMRA TaRMS specifications. <strong>The Service does not constitute professional tax, legal, or accounting advice.</strong>
        </p>
        <p>
          <strong>Exchange Rates:</strong> The "Auto-Fetch" feature provides exchange rate data from third-party sources for convenience. 
          Zim-PayConnect does not guarantee the accuracy, timeliness, or availability of these rates. You are responsible for verifying 
          that the rate used matches the official rate required by ZIMRA for your specific transaction date.
        </p>
        <p>
          While we strive to keep our tax tables and formulas up to date with current legislation, you are solely responsible for 
          verifying the accuracy of all outputs and ensuring compliance with all applicable laws and regulations.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold">4. Limitation of Liability</h2>
        <p className="uppercase font-medium">
          To the maximum extent permitted by applicable law, in no event shall Zim-PayConnect, its owners, operators, affiliates, 
          agents, or employees be liable for any indirect, punitive, incidental, special, consequential, or exemplary damages, 
          including without limitation damages for loss of profits, goodwill, use, data, or other intangible losses.
        </p>
        <div className="bg-muted p-4 rounded-md border">
          <p className="font-bold">
            Cap on Liability: Under no circumstances will Zim-PayConnect's total liability to you for any claims arising out of 
            or relating to the use of the Service exceed the amount of the subscription fee paid by you to Zim-PayConnect in the 
            one (1) month prior to the event giving rise to the claim.
          </p>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold">5. Data Handling</h2>
        <p>
          You acknowledge and agree that the Service operates on an ephemeral basis. We do not retain your payroll data after processing. 
          You are solely responsible for maintaining your own records and backups of all data submitted to and generated by the Service 
          as required by law.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold">6. Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless Zim-PayConnect and its owners from any claims, damages, liabilities, costs, 
          or expenses (including reasonable legal fees) arising from your use of the Service or your violation of these Terms.
        </p>
      </section>
    </div>
  );
}
